### ISSUE TITLE
Investigate and possibly implement fitting of sines and cosines as an alternative to aipy's CLEAN in uvtools.dspec.high_pass_fourier_filter

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/uvtools#17]

**Comment by nkern** [comment]
If you are interested in comparison, I also have an iterative fourier filtering code which I've compared to `aipy.deconv.clean` and get similar results and I think its a *little* quicker..
https://github.com/HERA-Team/hera_sandbox/blob/master/nsk/scripts/fourier_interp.py

**Comment by philbull** [comment]
See PR #26 which addresses this.

**Comment by plaplant** [comment]
This was addressed with #26, so I'm closing this issue.
